### ISSUE TITLE
table

### ISSUE THREAD

**Issue by Ahmedmedhat187** [laiiihz/sunmi_printer_service#2]
Hi laiiihz,

I have Sunmi V2 Pro. Could you please tell me how to print table and Image

**Comment by laiiihz** [comment]
im working on a new version of sunmi service,and i will add this feature this week (if i have time 😂 ) @Ahmedmedhat187

**Comment by laiiihz** [comment]
try the new version of this package 😆  @Ahmedmedhat187 

sunmi_printer_service: ^0.1.3

```dart
printColumnsText(
    text: [ 'a', 'b', 'c' ],
    width: [ 4, 4, 8 ],
    align: [ 1, 1, 1 ]
)
printBitmap(image)
```

**Comment by laiiihz** [comment]
im closing this issue🤣
